const PROMPT_ACTIONS = [
  { title: 'enhancer', key: 'IMPROVE', value: 'improve writing for the following text' },
  { title: 'analysis', key: 'ANALYSIS', value: 'perform bullet point analysis of the following text' },
  { title: 'spellcheck', key: 'FIX_SPELLING', value: 'fix spelling and grammar in the following text' },
  { title: 'responder', key: 'WRITE_RESPONSE', value: 'write response to a following message' },
  { title: 'shorten', key: 'MAKE_SHORTER', value: 'make following text shorter' },
  { title: 'lengthen', key: 'MAKE_LONGER', value: 'make following text longer' },
  { title: 'tonality', key: 'CHANGE_TONE', value: 'change tone of the following text' },
  { title: 'simplify', key: 'SIMPLIFY', value: 'simplify language of the following text' },
  { title: 'summarize', key: 'SUMMARIZE', value: 'summarize the following text' },
  { title: 'translate', key: 'TRANSLATE', value: 'translate the following text' },
  { title: 'sentiment', key: 'SENTIMENT', value: 'write a brief sentiment analysis, answer only with emotion and it scaled (1 to 5), for example: happy, 4' },
  { title: 'generate action point', key: 'ACTION_POINT', value: 'generate action point for given text' },
  { title: 'explaination', key: 'EXPLAIN', value: 'explain following text in simple terms' },
  { title: 'continuation', key: 'CONTINUE_WRITING', value: 'continue writing the following text' },
  { title: 'brainstorm', key: 'BRAINSTORM_IDEAS', value: 'brain storm ideas on the following text' },
  { title: 'blog', key: 'BLOG_POST', value: 'write a blog post based on the following text' },
  { title: 'essay', key: 'ESSAY', value: 'write a essay based on the following text' },
  { title: 'import', key: 'ESSAY', value: 'add folder to memory' },
  { title: 'deploy', key: 'ESSAY', value: 'deploy generated code from local folder' },
];
